# Generated by Django 4.1.7 on 2023-05-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='name',
            field=models.CharField(default='UFO', max_length=40),
        ),
    ]
