# Generated by Django 4.1.7 on 2023-05-12 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cryptocurrencymarketinfo_cryptocurrency_coin_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_id', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=40)),
                ('symbol', models.CharField(max_length=18)),
                ('image', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='CoinOHLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('open', models.DecimalField(decimal_places=8, max_digits=64)),
                ('high', models.DecimalField(decimal_places=8, max_digits=64)),
                ('low', models.DecimalField(decimal_places=8, max_digits=64)),
                ('close', models.DecimalField(decimal_places=8, max_digits=64)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coin')),
            ],
        ),
        migrations.RenameModel(
            old_name='CryptoCurrencyMarketInfo',
            new_name='CoinMarketInfo',
        ),
        migrations.DeleteModel(
            name='CryptoCurrency',
        ),
        migrations.AddField(
            model_name='coin',
            name='marketInfo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.coinmarketinfo'),
        ),
    ]
