# Generated by Django 4.1.7 on 2023-05-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_coin_coinohlc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='coin_id',
        ),
        migrations.AlterField(
            model_name='coin',
            name='image',
            field=models.CharField(max_length=256),
        ),
    ]
