# Generated by Django 4.1.7 on 2023-05-12 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_coin_coin_id_alter_coin_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='marketInfo',
            new_name='market_info',
        ),
    ]
