# Generated by Django 4.1.7 on 2023-05-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_coin_market_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinmarketinfo',
            name='circulating_supply',
            field=models.DecimalField(decimal_places=8, max_digits=128),
        ),
        migrations.AlterField(
            model_name='coinmarketinfo',
            name='current_price',
            field=models.DecimalField(decimal_places=8, max_digits=128),
        ),
        migrations.AlterField(
            model_name='coinmarketinfo',
            name='market_cap',
            field=models.DecimalField(decimal_places=8, max_digits=128),
        ),
        migrations.AlterField(
            model_name='coinmarketinfo',
            name='market_cap_change_24h',
            field=models.DecimalField(decimal_places=8, max_digits=128),
        ),
        migrations.AlterField(
            model_name='coinmarketinfo',
            name='price_change_24h',
            field=models.DecimalField(decimal_places=8, max_digits=128),
        ),
        migrations.AlterField(
            model_name='coinmarketinfo',
            name='total_volume',
            field=models.DecimalField(decimal_places=8, max_digits=128),
        ),
        migrations.AlterField(
            model_name='coinohlc',
            name='close',
            field=models.DecimalField(decimal_places=8, max_digits=128),
        ),
        migrations.AlterField(
            model_name='coinohlc',
            name='high',
            field=models.DecimalField(decimal_places=8, max_digits=128),
        ),
        migrations.AlterField(
            model_name='coinohlc',
            name='low',
            field=models.DecimalField(decimal_places=8, max_digits=128),
        ),
        migrations.AlterField(
            model_name='coinohlc',
            name='open',
            field=models.DecimalField(decimal_places=8, max_digits=128),
        ),
    ]
