# Generated by Django 4.1.7 on 2023-05-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_coinmarketinfo_circulating_supply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinmarketinfo',
            name='name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
