# Generated by Django 4.1.7 on 2023-05-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_coinmarketinfo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinohlc',
            name='coin',
        ),
        migrations.DeleteModel(
            name='Coin',
        ),
        migrations.DeleteModel(
            name='CoinMarketInfo',
        ),
        migrations.DeleteModel(
            name='CoinOHLC',
        ),
    ]
