# Generated by Django 4.2.1 on 2023-05-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_prediction_forecast_date'),
        ('api', '0014_alter_favoritecrypto_unique_together'),
    ]

    operations = [
    ]
